language: scala
scala:
  # https://github.com/non/spire/pull/413#issuecomment-89896773
  - 2.10.2
  - 2.11.6
script:
  - if [[ "$TRAVIS_SCALA_VERSION" == "2.10.2"
    ]]; then
      sbt ++$TRAVIS_SCALA_VERSION validate ;
    else
      sbt ++$TRAVIS_SCALA_VERSION coverage validate coverageReport && bash <(curl -s https://codecov.io/bash) ;
    fi
notifications:
  irc:
    channels:
      - "chat.freenode.net#spire-math"
    on_success: change
    on_failure: always
sudo: false
